   name: Build Android APK

   on:
     workflow_dispatch:

   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         
         - name: Set up JDK 11
           uses: actions/setup-java@v3
           with:
             distribution: 'temurin'
             java-version: '11'
             
         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
             node-version: '16'
             
         - name: Debug - List Files
           run: ls -la
           
         - name: Debug - List Android Directory
           run: ls -la android || echo "Android directory not found"
           
         - name: Create Directories
           run: |
             mkdir -p android/app/src/main/res
             mkdir -p android/gradle/wrapper
           
         - name: Install dependencies
           run: npm install || echo "NPM install failed, continuing"
           
         - name: Create gradle-wrapper.jar
           run: |
             touch android/gradle/wrapper/gradle-wrapper.jar
             echo "Created placeholder gradle-wrapper.jar"
             
         - name: Create gradle-wrapper.properties
           run: |
             echo "distributionBase=GRADLE_USER_HOME" > android/gradle/wrapper/gradle-wrapper.properties
             echo "distributionPath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
             echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-all.zip" >> android/gradle/wrapper/gradle-wrapper.properties
             echo "zipStoreBase=GRADLE_USER_HOME" >> android/gradle/wrapper/gradle-wrapper.properties
             echo "zipStorePath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
           
         - name: Create debug keystore
           run: |
             mkdir -p android/app
             keytool -genkeypair -v -storetype PKCS12 -keystore android/app/debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
             
         - name: Upload Debug Keystore
           uses: actions/upload-artifact@v3
           with:
             name: debug-keystore
             path: android/app/debug.keystore
