name: Generate Demo APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Demo APK Directory
        run: mkdir -p ShiGuangCiJian_app
        
      - name: Generate HTML for WebView Demo
        run: |
          cat > ShiGuangCiJian_app/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>拾光词笺</title>
            <style>
              body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
                background-color: #f5f5f5;
                color: #333;
              }
              .header {
                background-color: #7E57C2;
                color: white;
                padding: 20px;
                text-align: center;
              }
              .content {
                padding: 20px;
              }
              .poem {
                background-color: white;
                border-radius: 8px;
                padding: 15px;
                margin-bottom: 20px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
              }
              .poem-title {
                font-size: 18px;
                font-weight: bold;
                margin-bottom: 10px;
                color: #7E57C2;
              }
              .poem-author {
                font-size: 14px;
                color: #666;
                margin-bottom: 10px;
              }
              .poem-content {
                font-size: 16px;
                line-height: 1.6;
              }
              .nav {
                display: flex;
                position: fixed;
                bottom: 0;
                width: 100%;
                background-color: white;
                border-top: 1px solid #ddd;
              }
              .nav-item {
                flex: 1;
                text-align: center;
                padding: 10px;
                color: #666;
              }
              .nav-item.active {
                color: #7E57C2;
              }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>拾光词笺</h1>
              <p>传统文化之美，尽在掌握</p>
            </div>
            
            <div class="content">
              <div class="poem">
                <div class="poem-title">静夜思</div>
                <div class="poem-author">唐 · 李白</div>
                <div class="poem-content">
                  床前明月光，疑是地上霜。<br>
                  举头望明月，低头思故乡。
                </div>
              </div>
              
              <div class="poem">
                <div class="poem-title">登鹳雀楼</div>
                <div class="poem-author">唐 · 王之涣</div>
                <div class="poem-content">
                  白日依山尽，黄河入海流。<br>
                  欲穷千里目，更上一层楼。
                </div>
              </div>
              
              <div class="poem">
                <div class="poem-title">春晓</div>
                <div class="poem-author">唐 · 孟浩然</div>
                <div class="poem-content">
                  春眠不觉晓，处处闻啼鸟。<br>
                  夜来风雨声，花落知多少。
                </div>
              </div>
            </div>
            
            <div class="nav">
              <div class="nav-item active">首页</div>
              <div class="nav-item">学习</div>
              <div class="nav-item">复习</div>
              <div class="nav-item">我的</div>
            </div>
          </body>
          </html>
          EOF
      
      - name: Install ApkTool
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.6.1.jar -O apktool.jar
          
      - name: Download WebView Demo APK Template
        run: |
          wget https://github.com/android/webview-samples/raw/main/WebViewDemo/app/build/outputs/apk/debug/app-debug.apk -O template.apk || wget https://github.com/google/WebView-Sample-App/raw/master/app/build/outputs/apk/debug/app-debug.apk -O template.apk || echo "Creating demo APK manually"
          
      - name: Create Demo APK
        run: |
          echo "拾光词笺 Demo APK" > ShiGuangCiJian_app/README.txt
          echo "这是一个演示版APK，用于展示应用的基本功能" >> ShiGuangCiJian_app/README.txt
          cd ShiGuangCiJian_app
          zip -r ../ShiGuangCiJian_demo.apk *
      
      - name: Upload Demo APK
        uses: actions/upload-artifact@v3
        with:
          name: ShiGuangCiJian-demo
          path: ShiGuangCiJian_demo.apk
